[2025-07-28T12:13:17.692+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: show_recent_logs.show_recent_logs manual__2025-07-28T12:13:16.872853+00:00 [queued]>
[2025-07-28T12:13:17.699+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: show_recent_logs.show_recent_logs manual__2025-07-28T12:13:16.872853+00:00 [queued]>
[2025-07-28T12:13:17.699+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-07-28T12:13:17.712+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): show_recent_logs> on 2025-07-28 12:13:16.872853+00:00
[2025-07-28T12:13:17.718+0000] {standard_task_runner.py:57} INFO - Started process 1834 to run task
[2025-07-28T12:13:17.720+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'show_recent_logs', 'show_recent_logs', 'manual__2025-07-28T12:13:16.872853+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/log_reader_dag.py', '--cfg-path', '/tmp/tmpk3o02kz9']
[2025-07-28T12:13:17.722+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask show_recent_logs
[2025-07-28T12:13:17.770+0000] {task_command.py:415} INFO - Running <TaskInstance: show_recent_logs.show_recent_logs manual__2025-07-28T12:13:16.872853+00:00 [running]> on host 00b4b9fb4b52
[2025-07-28T12:13:17.853+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='show_recent_logs' AIRFLOW_CTX_TASK_ID='show_recent_logs' AIRFLOW_CTX_EXECUTION_DATE='2025-07-28T12:13:16.872853+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-28T12:13:16.872853+00:00'
[2025-07-28T12:13:17.854+0000] {logging_mixin.py:151} INFO - logs are here:  [(1, 'docker-kafka-1', '[2025-07-28 11:55:37,263] INFO [GroupCoordinator 1]: Stabilized group ***_consumer generation 3 (__consumer_offsets-6) with 1 members (kafka.coordinator.group.GroupCoordinator)', '2025-07-28 11:55:37.263931'), (2, 'docker-kafka-1', '[2025-07-28 11:55:37,264] INFO [GroupCoordinator 1]: Assignment received from leader kafka-python-2.2.15-8e5b8a3a-d2c0-4aa8-99ad-f08ed3075cdc for group ***_consumer for generation 3. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)', '2025-07-28 11:55:37.278939'), (3, 'docker-consumer-1', "Received app review: {'reviewId': '12c1e2dd-d123-4ee5-94c8-fd93ea3641aa', 'userName': 'Gullazannat Mukta', 'content': 'very nice useful app', 'score': 5, 'thumbsUpCount': 0, 'at': '2025-07-27T09:32:18', 'timestamp': '2025-07-28T09:48:00.814672'}", '2025-07-28 11:55:37.309163'), (4, 'docker-consumer-1', 'Traceback (most recent call last):', '2025-07-28 11:55:37.314105'), (5, 'docker-consumer-1', 'File "/app/main.py", line 54, in <module>', '2025-07-28 11:55:37.318678'), (6, 'docker-consumer-1', 'cur.execute(', '2025-07-28 11:55:37.323324'), (7, 'docker-consumer-1', 'TypeError: not all arguments converted during string formatting', '2025-07-28 11:55:37.329326'), (8, 'docker-kafka-1', '[2025-07-28 11:55:47,265] INFO [GroupCoordinator 1]: Member kafka-python-2.2.15-8e5b8a3a-d2c0-4aa8-99ad-f08ed3075cdc in group ***_consumer has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)', '2025-07-28 11:55:47.266031'), (9, 'docker-kafka-1', '[2025-07-28 11:55:47,265] INFO [GroupCoordinator 1]: Preparing to rebalance group ***_consumer in state PreparingRebalance with old generation 3 (__consumer_offsets-6) (reason: removing member kafka-python-2.2.15-8e5b8a3a-d2c0-4aa8-99ad-f08ed3075cdc on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)', '2025-07-28 11:55:47.283075'), (10, 'docker-kafka-1', '[2025-07-28 11:55:47,265] INFO [GroupCoordinator 1]: Group ***_consumer with generation 4 is now empty (__consumer_offsets-6) (kafka.coordinator.group.GroupCoordinator)', '2025-07-28 11:55:47.286930')]
[2025-07-28T12:13:17.854+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-07-28T12:13:17.866+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=show_recent_logs, task_id=show_recent_logs, execution_date=20250728T121316, start_date=20250728T121317, end_date=20250728T121317
[2025-07-28T12:13:17.892+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-07-28T12:13:17.908+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
